# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-12 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ips',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.IntegerField()),
                ('person', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50, null=True)),
                ('add_date', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
