# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-12 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipmanage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ips',
            old_name='address',
            new_name='mask',
        ),
        migrations.AddField(
            model_name='ips',
            name='ip_addr',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ips',
            name='seq',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ips',
            name='person',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
