# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-12 05:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipmanage', '0002_auto_20160412_0503'),
    ]

    operations = [
        migrations.CreateModel(
            name='nets',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=200)),
                ('begin', models.IntegerField()),
                ('end', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='ips',
            name='mask',
        ),
        migrations.AddField(
            model_name='ips',
            name='net',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ipmanage.nets'),
            preserve_default=False,
        ),
    ]
