# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-12 05:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipmanage', '0003_auto_20160412_0528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ips',
            name='department',
        ),
    ]
