# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-12 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipmanage', '0004_remove_ips_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nets',
            name='begin',
        ),
        migrations.RemoveField(
            model_name='nets',
            name='end',
        ),
        migrations.AddField(
            model_name='nets',
            name='gateway',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='nets',
            name='mask',
            field=models.IntegerField(null=True),
        ),
    ]
