# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-12 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipmanage', '0005_auto_20160412_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nets',
            name='mask',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
