# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-13 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipmanage', '0006_auto_20160412_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ips',
            name='seq',
            field=models.BigIntegerField(),
        ),
    ]
