# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-18 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipmanage', '0007_auto_20160413_0720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nets',
            name='gateway',
        ),
        migrations.RemoveField(
            model_name='nets',
            name='mask',
        ),
        migrations.AddField(
            model_name='nets',
            name='name',
            field=models.CharField(default='empty', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nets',
            name='desc',
            field=models.CharField(max_length=400),
        ),
    ]
