# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-19 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipmanage', '0008_auto_20160418_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nets',
            name='desc',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
